-- MySQL Script generated by MySQL Workbench
-- Fri Feb 12 11:19:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eezyshipper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eezyshipper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eezyshipper` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `eezyshipper` ;

-- -----------------------------------------------------
-- Table `eezyshipper`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`countries` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`administration` (
  `administration_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `brief` MEDIUMTEXT NULL,
  `col` VARCHAR(45) NULL,
  PRIMARY KEY (`administration_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `password` VARCHAR(255) NOT NULL,
  `gender` ENUM('0', '1', '2') NULL,
  `dob` DATE NULL,
  `admin_id` INT NULL DEFAULT NULL,
  `status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '0= incomplete\n1=active\n-1= de-active',
  `country_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `address_ln_1` VARCHAR(90) NULL,
  `address_ln-2` VARCHAR(90) NULL,
  `address_ln_3` VARCHAR(60) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`users_id`, `admin_id`, `country_id`),
  INDEX `fk_country_id_idx` (`country_id` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `pk_users_adminstration_idx` (`admin_id` ASC) ,
  CONSTRAINT `fk_country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_users_adminstration_idx`
    FOREIGN KEY (`admin_id`)
    REFERENCES `eezyshipper`.`administration` (`administration_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`warehouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`warehouses` (
  `wh_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NULL,
  `wh_type` ENUM('0', '1', '2', '3') NULL DEFAULT '3' COMMENT '0= default wh\n1=Pickup point\n2= Source Point\n3= both 1 and 2. Can be use as general pupose',
  `status` ENUM('0', '1') NULL DEFAULT '1' COMMENT 'Is this warehouse active or deactive\n0=active\n-1= de-active',
  `country_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `address_ln_1` VARCHAR(90) NULL,
  `address_ln-2` VARCHAR(90) NULL,
  `address_ln_3` VARCHAR(60) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`wh_id`, `country_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`suppliers` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `status` ENUM('0', '1') NULL DEFAULT '1' COMMENT 'Does Supplier active or deactive\n0=active\n-1= inactive',
  `country_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `address_ln_1` VARCHAR(90) NULL,
  `address_ln-2` VARCHAR(90) NULL,
  `address_ln_3` VARCHAR(60) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`supplier_id`, `country_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_suppliers_country_id_idx` (`country_id` ASC) ,
  CONSTRAINT `pk_tns_consignment_consignment_idx`
    FOREIGN KEY (`country_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`doc_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`doc_type` (
  `doc_type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  `brief` MEDIUMTEXT NULL,
  PRIMARY KEY (`doc_type_id`),
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`varifies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`varifies` (
  `varifies_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `document_type_id` INT NOT NULL,
  `f_name` VARCHAR(45) NULL,
  `l_name` VARCHAR(45) NULL,
  `doc_no` VARCHAR(30) NULL,
  `valid_from` DATE NULL,
  `valid_till` DATE NULL,
  `doc_imgs` VARCHAR(255) NOT NULL COMMENT 'Maximum 4 images a user can upload and total images size would be 20MB',
  `varification_status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '0= Not Varified\n1=varified\n-1=Varification Failed',
  `varified_by` INT NULL,
  `varified_at` DATETIME NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`varifies_id`, `document_type_id`, `user_id`, `varified_by`),
  INDEX `pk_doc_type_id_idx` (`document_type_id` ASC) ,
  INDEX `pk_identity_varified_by_idx` (`varified_by` ASC) ,
  INDEX `pk_vf_user_id_idx` (`user_id` ASC) ,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) ,
  CONSTRAINT `pk_doc_type_id`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `eezyshipper`.`doc_type` (`doc_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_identity_varified_by`
    FOREIGN KEY (`varified_by`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_vf_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`notifications` (
  `notifications_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NULL,
  `brief` MEDIUMTEXT NULL,
  `priority` ENUM('0', '1', '2', '3', '4') NULL DEFAULT '0' COMMENT '0=info\n1= warning\n2= Failed\n3= Success\n4= Next Step',
  `notification_status` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0= active\n1=inactive',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`notifications_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`user_notify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`user_notify` (
  `user_notify_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `notification_id` INT NOT NULL,
  `notification_status` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0= read\n1=unread',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_notify_id`, `user_id`, `notification_id`),
  INDEX `pk_notify_user_id_idx` (`user_id` ASC) ,
  INDEX `pk_notification_id_idx` (`notification_id` ASC) ,
  CONSTRAINT `pk_notify_user_id_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_notification_id_idx`
    FOREIGN KEY (`notification_id`)
    REFERENCES `eezyshipper`.`notifications` (`notifications_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`user_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`user_cards` (
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `card_type` ENUM('0', '1') NOT NULL COMMENT '0= VISA\n1=MASTER',
  `card_number` VARCHAR(16) NOT NULL,
  `expire` VARCHAR(5) NOT NULL,
  `cvc` VARCHAR(4) NOT NULL,
  `is_default` ENUM('0', '1') NULL DEFAULT '0' COMMENT 'is This Card is your default card\n0= No\n1=yes',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`card_id`, `user_id`),
  INDEX `pk_cards_user_id_idx` (`user_id` ASC) ,
  CONSTRAINT `pk_cards_user_id_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`subcirptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`subcirptions` (
  `subcirptions_id` INT NOT NULL AUTO_INCREMENT,
  `f_name` VARCHAR(45) NULL,
  `l_name` VARCHAR(45) NULL,
  `doc_no` VARCHAR(30) NULL,
  `valid_from` DATE NULL,
  `valid_till` DATE NULL,
  `doc_imgs` VARCHAR(255) NOT NULL COMMENT 'Maximum 4 images a user can upload and total images size would be 20MB',
  `varification_status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '0= Not Varified\n1=varified\n-1=Varification Failed',
  `varified_at` DATETIME NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`subcirptions_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `payment_for` ENUM('0', '1') NOT NULL COMMENT '0=Subscription\n1=Order',
  `card_id` INT NULL,
  `service_id` INT NULL COMMENT 'Order id / user_subscription id \n\nservice_id + payment_id ',
  `amount` FLOAT NOT NULL,
  `payment_status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '-1 = Payment failed\n0= Waiting for payment\n1=payed',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`, `user_id`),
  INDEX `pk_subscription_user_id_idx` (`user_id` ASC) ,
  INDEX `pk_card_id_for_payment_idx` (`card_id` ASC) ,
  CONSTRAINT `pk_subscription_user_id_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_card_id_for_payment_idx`
    FOREIGN KEY (`card_id`)
    REFERENCES `eezyshipper`.`user_cards` (`card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`user_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`user_subscription` (
  `user_subscribe_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `subscription_id` INT NOT NULL,
  `valid_from` DATETIME NULL,
  `valid_till` DATETIME NULL,
  `amount` FLOAT NULL,
  `subscription_status` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0=waiting for payment\n1= Active\n-1= De-Active/ Expires',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`user_subscribe_id`, `user_id`, `subscription_id`, `payment_id`),
  INDEX `pk_subscribed_user_id_idx` (`user_id` ASC) ,
  INDEX `pk_subscription_idx` (`subscription_id` ASC) ,
  INDEX `fk_user_subscription_payments1_idx` (`payment_id` ASC) ,
  CONSTRAINT `pk_subscribed_user_id_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_subscription_idx`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `eezyshipper`.`subcirptions` (`subcirptions_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_subscription_payments1_idx`
    FOREIGN KEY (`payment_id`)
    REFERENCES `eezyshipper`.`payments` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`supplier_charges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`supplier_charges` (
  `supplier_charge_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `route_from_id` INT NOT NULL,
  `route_to_id` INT NOT NULL,
  `charge_status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '0= active\n1=inactive\n',
  `weight_r_from` TINYINT(1) NOT NULL,
  `weight_r_to` TINYINT(5) NOT NULL,
  `rate` FLOAT NULL,
  `markup_charge` FLOAT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`supplier_charge_id`, `supplier_id`, `route_from_id`, `route_to_id`),
  INDEX `fk_supplier_charges_suppliers1_idx` (`supplier_id` ASC) ,
  INDEX `fk_supplier_charges_countries1_idx` (`route_from_id` ASC) ,
  INDEX `fk_supplier_charges_countries2_idx` (`route_to_id` ASC) ,
  UNIQUE INDEX `route_from_id_UNIQUE` (`route_from_id` ASC) ,
  UNIQUE INDEX `routeto_id_UNIQUE` (`route_to_id` ASC) ,
  UNIQUE INDEX `supplier_id_UNIQUE` (`supplier_id` ASC) ,
  CONSTRAINT `fk_supplier_charges_suppliers1_idx`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `eezyshipper`.`suppliers` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_charges_countries1_idx`
    FOREIGN KEY (`route_from_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_charges_countries2_idx`
    FOREIGN KEY (`route_to_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`percels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`percels` (
  `percels_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `wh_id` INT NOT NULL,
  `valid_till` DATE NULL,
  `percel_status` ENUM('0', '1', '-1', '-2') NULL DEFAULT '0' COMMENT '0= waiting for Enter Data\n1= placed order\n-1= rejected roduct\n-2 = Returned to Origin/Ecommerce ',
  `returned_reson` MEDIUMTEXT NULL COMMENT 'Is optional field. If a product is returned due to Damage or Prohabited product. Explain reason',
  `weight` FLOAT NULL,
  `dimension_x` FLOAT NULL,
  `dimension_y` FLOAT NULL,
  `dimension_z` FLOAT NULL,
  `volumetric_weight` FLOAT NULL,
  `supplier_charge_id` INT NULL,
  `cost` FLOAT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`percels_id`, `user_id`, `wh_id`),
  INDEX `pk_percel_user_idx` (`user_id` ASC) ,
  INDEX `pk_percel_wh_idx` (`wh_id` ASC) ,
  INDEX `pk_percel_s_charge_idx` (`supplier_charge_id` ASC) ,
  CONSTRAINT `pk_percel_user_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_percel_wh_idx`
    FOREIGN KEY (`wh_id`)
    REFERENCES `eezyshipper`.`warehouses` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_percel_s_charge_idx`
    FOREIGN KEY (`supplier_charge_id`)
    REFERENCES `eezyshipper`.`supplier_charges` (`supplier_charge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`consignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`consignments` (
  `consignments_id` INT NOT NULL AUTO_INCREMENT,
  `prefix` VARCHAR(12) NOT NULL,
  `number` INT(9) NULL DEFAULT 1,
  `consignment_status` ENUM('0', '1') NULL DEFAULT '1',
  `open_day` ENUM('0', '1', '2', '3', '4', '5', '6') NOT NULL,
  `open_time` TIME NOT NULL,
  `closing_time` TIME NOT NULL,
  `closing_day` ENUM('0', '1', '2', '3', '4', '5', '6') NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`consignments_id`),
  UNIQUE INDEX `prefix_UNIQUE` (`prefix` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`consignment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`consignment_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brief` VARCHAR(500) NOT NULL,
  `status_type` ENUM('0', '1', '-1', '2') NOT NULL COMMENT '0= assigned\n2= process step\n1=final step\n-1=failed',
  `step_no` TINYINT(1) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`tns_consignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`tns_consignment` (
  `tns_cons_id` INT NOT NULL AUTO_INCREMENT,
  `consignments_id` INT NOT NULL,
  `consignment_number` VARCHAR(45) NOT NULL,
  `consignment_status_id` INT NOT NULL,
  `eta` DATE NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `route_source_id` INT NOT NULL,
  `route_destination_id` INT NOT NULL,
  PRIMARY KEY (`tns_cons_id`, `consignments_id`, `consignment_status_id`, `route_source_id`, `route_destination_id`),
  INDEX `fk_tns_consignment_consignments1_idx` (`consignments_id` ASC) ,
  INDEX `fk_tns_consignment_consignment_status1_idx` (`consignment_status_id` ASC) ,
  INDEX `fk_tns_consignment_countries1_idx` (`route_source_id` ASC) ,
  INDEX `fk_tns_consignment_countries2_idx` (`route_destination_id` ASC) ,
  CONSTRAINT `fk_tns_consignment_consignments1`
    FOREIGN KEY (`consignments_id`)
    REFERENCES `eezyshipper`.`consignments` (`consignments_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tns_consignment_consignment_status1`
    FOREIGN KEY (`consignment_status_id`)
    REFERENCES `eezyshipper`.`consignment_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tns_consignment_countries1`
    FOREIGN KEY (`route_source_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tns_consignment_countries2`
    FOREIGN KEY (`route_destination_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `source_wh_id` INT NOT NULL,
  `destination_wh_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `percels_id` INT NOT NULL,
  `supplier_charge_id` INT NOT NULL,
  `charge` FLOAT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `col` VARCHAR(45) NULL,
  `tns_cons_id` INT NOT NULL,
  `tns_consignment_status_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `user_id`, `source_wh_id`, `destination_wh_id`, `payment_id`, `percels_id`, `supplier_charge_id`),
  INDEX `pk_order_to_user_idx` (`user_id` ASC) ,
  INDEX `pk_order_to_source_wh_id_idx` (`source_wh_id` ASC) ,
  INDEX `pk_order_to_destination_wh_id_idx` (`destination_wh_id` ASC) ,
  INDEX `fk_orders_payments1_idx` (`payment_id` ASC) ,
  UNIQUE INDEX `payment_id_UNIQUE` (`payment_id` ASC) ,
  INDEX `fk_orders_percels1_idx` (`percels_id` ASC) ,
  INDEX `fk_orders_supplier_charges1_idx` (`supplier_charge_id` ASC) ,
  INDEX `fk_orders_tns_consignment1_idx` (`tns_cons_id` ASC, `tns_consignment_status_id` ASC) ,
  CONSTRAINT `pk_order_to_user_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_order_to_source_wh_id_idx`
    FOREIGN KEY (`source_wh_id`)
    REFERENCES `eezyshipper`.`warehouses` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_order_to_destination_wh_id_idx`
    FOREIGN KEY (`destination_wh_id`)
    REFERENCES `eezyshipper`.`warehouses` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_payments1_idx`
    FOREIGN KEY (`payment_id`)
    REFERENCES `eezyshipper`.`payments` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_percels1_idx`
    FOREIGN KEY (`percels_id`)
    REFERENCES `eezyshipper`.`percels` (`percels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_supplier_charges1_idx`
    FOREIGN KEY (`supplier_charge_id`)
    REFERENCES `eezyshipper`.`supplier_charges` (`supplier_charge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_tns_consignment1`
    FOREIGN KEY (`tns_cons_id` , `tns_consignment_status_id`)
    REFERENCES `eezyshipper`.`tns_consignment` (`tns_cons_id` , `consignment_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`packages` (
  `varifies_id` INT NOT NULL AUTO_INCREMENT,
  `percel_id` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `content` VARCHAR(30) NULL,
  `product_image` VARCHAR(255) NULL COMMENT 'Maximum 4 images a user can upload and total images size would be 20MB',
  `product_status` ENUM('0', '1', '-1') NULL DEFAULT '1' COMMENT '0=Damaged/other\n1=ok\n-1=prohibited',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`varifies_id`, `percel_id`),
  INDEX `pk_package_percel_idx` (`percel_id` ASC) ,
  CONSTRAINT `pk_package_percel_idx`
    FOREIGN KEY (`percel_id`)
    REFERENCES `eezyshipper`.`percels` (`percels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`resources` (
  `resources_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brief` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`resources_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`administrative_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`administrative_access` (
  `access_id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `premit_for` ENUM('B', 'R', 'E', 'A', 'D') NOT NULL COMMENT 'B = Browe Resource\nR = Read Details for that resource\nE = Edit Resource Information\nA = Create New Record\nD = Delete Record',
  `premission_status` ENUM('0', '1') NULL DEFAULT '1',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`access_id`, `users_id`, `admin_id`, `resources_id`),
  INDEX `fk_administrative_access_users1` (`users_id` ASC, `admin_id` ASC) ,
  INDEX `fk_administrative_access_resources1` (`resources_id` ASC) ,
  CONSTRAINT `fk_administrative_access_users1`
    FOREIGN KEY (`users_id` , `admin_id`)
    REFERENCES `eezyshipper`.`users` (`users_id` , `admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrative_access_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `eezyshipper`.`resources` (`resources_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
