-- MySQL Script generated by MySQL Workbench
-- Sun Feb 14 12:11:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eezyshipper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eezyshipper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eezyshipper` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `eezyshipper` ;

-- -----------------------------------------------------
-- Table `eezyshipper`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`resources` (
  `resources_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brief` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`resources_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`administrative_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`administrative_access` (
  `access_id` INT NOT NULL AUTO_INCREMENT,
  `resources_id` INT NOT NULL,
  `premit_for` ENUM('B', 'R', 'E', 'A', 'D') NOT NULL COMMENT 'B = Browe Resource\nR = Read Details for that resource\nE = Edit Resource Information\nA = Create New Record\nD = Delete Record',
  `premission_status` ENUM('0', '1') NULL DEFAULT '1',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`access_id`, `resources_id`),
  INDEX `fk_administrative_access_resources1_idx` (`resources_id` ASC) ,
  CONSTRAINT `fk_administrative_access_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `eezyshipper`.`resources` (`resources_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`administration` (
  `administration_id` INT NOT NULL AUTO_INCREMENT,
  `resources_id` INT NOT NULL,
  `administrative_access_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `brief` MEDIUMTEXT NULL,
  `col` VARCHAR(45) NULL,
  PRIMARY KEY (`administration_id`, `resources_id`, `administrative_access_id`),
  INDEX `fk_administration_administrative_access1_idx` (`administrative_access_id` ASC, `resources_id` ASC) ,
  CONSTRAINT `fk_administration_administrative_access1`
    FOREIGN KEY (`administrative_access_id` , `resources_id`)
    REFERENCES `eezyshipper`.`administrative_access` (`access_id` , `resources_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`countries` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `administration_id` INT NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `password` VARCHAR(255) NOT NULL,
  `gender` ENUM('0', '1', '2') NULL,
  `dob` DATE NULL,
  `country_id` INT NOT NULL,
  `status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '0= incomplete\n1=active\n-1= de-active',
  `city` VARCHAR(45) NULL,
  `address_ln_1` VARCHAR(90) NULL,
  `address_ln-2` VARCHAR(90) NULL,
  `address_ln_3` VARCHAR(60) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`users_id`, `country_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_users_administration_idx` (`administration_id` ASC) ,
  INDEX `fk_users_countries1_idx` (`country_id` ASC) ,
  CONSTRAINT `fk_users_administration`
    FOREIGN KEY (`administration_id`)
    REFERENCES `eezyshipper`.`administration` (`administration_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`warehouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`warehouses` (
  `wh_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(20) NULL,
  `wh_type` ENUM('0', '1', '2', '3') NULL DEFAULT '3' COMMENT '0= default wh\n1=Pickup point\n2= Source Point\n3= both 1 and 2. Can be use as general pupose',
  `status` ENUM('0', '1') NULL DEFAULT '1' COMMENT 'Is this warehouse active or deactive\n0=active\n-1= de-active',
  `city` VARCHAR(45) NULL,
  `address_ln_1` VARCHAR(90) NULL,
  `address_ln-2` VARCHAR(90) NULL,
  `address_ln_3` VARCHAR(60) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `wh_country_id` INT NOT NULL,
  PRIMARY KEY (`wh_id`, `wh_country_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_warehouses_countries1_idx` (`wh_country_id` ASC) ,
  CONSTRAINT `fk_warehouses_countries1`
    FOREIGN KEY (`wh_country_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`suppliers` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `status` ENUM('0', '1') NULL DEFAULT '1' COMMENT 'Does Supplier active or deactive\n0=active\n-1= inactive',
  `city` VARCHAR(45) NULL,
  `address_ln_1` VARCHAR(90) NULL,
  `address_ln-2` VARCHAR(90) NULL,
  `address_ln_3` VARCHAR(60) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `countries_country_id` INT NOT NULL,
  PRIMARY KEY (`supplier_id`, `countries_country_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_suppliers_countries1_idx` (`countries_country_id` ASC) ,
  CONSTRAINT `fk_suppliers_countries1`
    FOREIGN KEY (`countries_country_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`doc_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`doc_type` (
  `doc_type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  `brief` MEDIUMTEXT NULL,
  PRIMARY KEY (`doc_type_id`),
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`varifies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`varifies` (
  `varifies_id` INT NOT NULL AUTO_INCREMENT,
  `f_name` VARCHAR(45) NULL,
  `l_name` VARCHAR(45) NULL,
  `doc_no` VARCHAR(30) NULL,
  `valid_from` DATE NULL,
  `valid_till` DATE NULL,
  `doc_imgs` VARCHAR(255) NOT NULL COMMENT 'Maximum 4 images a user can upload and total images size would be 20MB',
  `varification_status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '0= Not Varified\n1=varified\n-1=Varification Failed',
  `varified_at` DATETIME NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `doc_type_id` INT NOT NULL,
  `users_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`varifies_id`, `doc_type_id`),
  INDEX `fk_varifies_doc_type1_idx` (`doc_type_id` ASC) ,
  INDEX `fk_varifies_users1_idx` (`users_id` ASC) ,
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) ,
  CONSTRAINT `fk_varifies_doc_type1`
    FOREIGN KEY (`doc_type_id`)
    REFERENCES `eezyshipper`.`doc_type` (`doc_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_varifies_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`notifications` (
  `notifications_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `brief` MEDIUMTEXT NOT NULL,
  `priority` ENUM('0', '1', '2', '3', '4') NULL DEFAULT '0' COMMENT '0=info\n1= warning\n2= Failed\n3= Success\n4= Next Step',
  `notification_status` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0= active\n1=inactive',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`notifications_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`user_notify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`user_notify` (
  `user_notify_id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `notifications_id` INT NOT NULL,
  `notification_status` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0= read\n1=unread',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_notify_id`, `users_id`, `notifications_id`),
  INDEX `fk_user_notify_notifications1_idx` (`notifications_id` ASC) ,
  INDEX `fk_user_notify_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_user_notify_notifications1`
    FOREIGN KEY (`notifications_id`)
    REFERENCES `eezyshipper`.`notifications` (`notifications_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_notify_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`user_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`user_cards` (
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `card_type` ENUM('0', '1') NOT NULL COMMENT '0= VISA\n1=MASTER',
  `card_number` VARCHAR(16) NOT NULL,
  `expire` VARCHAR(5) NOT NULL,
  `cvc` VARCHAR(4) NOT NULL,
  `is_default` ENUM('0', '1') NULL DEFAULT '0' COMMENT 'is This Card is your default card\n0= No\n1=yes',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`card_id`, `users_id`),
  INDEX `fk_user_cards_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_user_cards_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`subcirptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`subcirptions` (
  `subcirptions_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_name` VARCHAR(45) NULL,
  `charge_type` ENUM('0', '1', '2') NULL COMMENT 'Subscription Charge Type\n==================\n0= Free\n1= Monthly\n2=Yearly',
  `monthly_charge` FLOAT NULL,
  `yearly_charge` FLOAT NULL,
  `is_default` ENUM('0', '1') NULL,
  `brief` MEDIUMTEXT NULL,
  `status` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0=inactive\n1=active\n',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`subcirptions_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `payment_for` ENUM('0', '1') NOT NULL COMMENT '0=Subscription\n1=Order',
  `service_id` INT NULL COMMENT 'Order id / user_subscription id \n\nservice_id + payment_id ',
  `amount` FLOAT NOT NULL,
  `payment_status` ENUM('0', '1', '-1') NULL DEFAULT '0' COMMENT '-1 = Payment failed\n0= Waiting for payment\n1=payed',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_card_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`, `users_id`),
  INDEX `fk_payments_user_cards1_idx` (`user_card_id` ASC) ,
  INDEX `fk_payments_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_payments_user_cards1`
    FOREIGN KEY (`user_card_id`)
    REFERENCES `eezyshipper`.`user_cards` (`card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`user_subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`user_subscription` (
  `user_subscribe_id` INT NOT NULL AUTO_INCREMENT,
  `valid_from` DATETIME NULL,
  `valid_till` DATETIME NULL,
  `amount` FLOAT NULL,
  `subscription_status` ENUM('0', '1') NULL DEFAULT '0' COMMENT '0=waiting for payment\n1= Active\n-1= De-Active/ Expires',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `subcirptions_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`user_subscribe_id`, `subcirptions_id`, `users_id`, `payment_id`),
  INDEX `fk_user_subscription_subcirptions1_idx` (`subcirptions_id` ASC) ,
  INDEX `fk_user_subscription_users1_idx` (`users_id` ASC) ,
  INDEX `fk_user_subscription_payments1_idx` (`payment_id` ASC) ,
  CONSTRAINT `fk_user_subscription_subcirptions1`
    FOREIGN KEY (`subcirptions_id`)
    REFERENCES `eezyshipper`.`subcirptions` (`subcirptions_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_subscription_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_subscription_payments1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `eezyshipper`.`payments` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`percels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`percels` (
  `percels_id` INT NOT NULL AUTO_INCREMENT,
  `valid_till` DATE NULL,
  `percel_status` ENUM('0', '1', '-1', '-2') NULL DEFAULT '0' COMMENT '0= waiting for Enter Data\n1= placed order\n-1= rejected roduct\n-2 = Returned to Origin/Ecommerce ',
  `returned_cause` MEDIUMTEXT NULL COMMENT 'Is optional field. If a product is returned due to Damage or Prohabited product. Explain reason',
  `percel_images` VARCHAR(255) NULL DEFAULT NULL,
  `weight` FLOAT NULL,
  `dimension_x` FLOAT NULL,
  `dimension_y` FLOAT NULL,
  `dimension_z` FLOAT NULL,
  `volumetric_weight` FLOAT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `warehouse_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`percels_id`, `warehouse_id`),
  INDEX `fk_percels_warehouses1_idx` (`warehouse_id` ASC) ,
  INDEX `fk_percels_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_percels_warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `eezyshipper`.`warehouses` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_percels_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`consignment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`consignment_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brief` VARCHAR(500) NOT NULL,
  `status_type` ENUM('0', '1', '-1', '2') NOT NULL COMMENT '0= assigned\n2= process step\n1=final step\n-1=failed',
  `step_no` TINYINT(1) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`consignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`consignments` (
  `consignments_id` INT NOT NULL AUTO_INCREMENT,
  `prefix` VARCHAR(12) NOT NULL,
  `number` INT(9) NULL DEFAULT 1,
  `consignment_status` ENUM('0', '1') NULL DEFAULT '1',
  `open_day` ENUM('0', '1', '2', '3', '4', '5', '6') NOT NULL,
  `open_time` TIME NOT NULL,
  `closing_time` TIME NOT NULL,
  `closing_day` ENUM('0', '1', '2', '3', '4', '5', '6') NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`consignments_id`),
  UNIQUE INDEX `prefix_UNIQUE` (`prefix` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`tns_consignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`tns_consignment` (
  `tns_cons_id` INT NOT NULL AUTO_INCREMENT,
  `consignment_number` VARCHAR(30) NOT NULL,
  `eta` DATE NULL,
  `consignment_status_id` INT NOT NULL,
  `consignments_id` INT NOT NULL,
  `cons_route_from_id` INT NOT NULL,
  `cons_route_to_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`tns_cons_id`, `consignment_number`, `consignment_status_id`, `consignments_id`, `cons_route_from_id`, `cons_route_to_id`),
  INDEX `fk_tns_consignment_consignment_status1_idx` (`consignment_status_id` ASC) ,
  INDEX `fk_tns_consignment_consignments1_idx` (`consignments_id` ASC) ,
  INDEX `fk_tns_consignment_countries1_idx` (`cons_route_from_id` ASC) ,
  INDEX `fk_tns_consignment_countries2_idx` (`cons_route_to_id` ASC) ,
  UNIQUE INDEX `consignment_number_UNIQUE` (`consignment_number` ASC) ,
  CONSTRAINT `fk_tns_consignment_consignment_status1`
    FOREIGN KEY (`consignment_status_id`)
    REFERENCES `eezyshipper`.`consignment_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tns_consignment_consignments1`
    FOREIGN KEY (`consignments_id`)
    REFERENCES `eezyshipper`.`consignments` (`consignments_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tns_consignment_countries1`
    FOREIGN KEY (`cons_route_from_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tns_consignment_countries2`
    FOREIGN KEY (`cons_route_to_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`supplier_charges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`supplier_charges` (
  `supplier_charge_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `reoute_from_country_id` INT NOT NULL,
  `reoute_to_country_id` INT NOT NULL,
  `charge_status` ENUM('0', '1') NULL DEFAULT '1' COMMENT '1= active\n0=inactive\n',
  `weight_from` TINYINT(1) NOT NULL,
  `weight_to` TINYINT(5) NOT NULL,
  `rate` FLOAT NOT NULL,
  `markup_charge` FLOAT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`supplier_charge_id`, `reoute_from_country_id`),
  INDEX `fk_supplier_charges_countries1_idx` (`reoute_from_country_id` ASC) ,
  INDEX `fk_supplier_charges_countries2_idx` (`reoute_to_country_id` ASC) ,
  INDEX `fk_supplier_charges_suppliers1_idx` (`supplier_id` ASC) ,
  CONSTRAINT `fk_supplier_charges_countries1`
    FOREIGN KEY (`reoute_from_country_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_charges_countries2`
    FOREIGN KEY (`reoute_to_country_id`)
    REFERENCES `eezyshipper`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_charges_suppliers1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `eezyshipper`.`suppliers` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `charge` FLOAT NULL,
  `col` VARCHAR(45) NULL,
  `payment_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `wh_origin_id` INT NOT NULL,
  `wh_destination_id` INT NULL DEFAULT NULL,
  `percels_id` INT NOT NULL,
  `order_price` FLOAT NULL,
  `tns_consignmen_id` INT NULL,
  `supplier_charge_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_status` ENUM('-1', '0', '1', '2', '3') NULL DEFAULT '0' COMMENT '-2= Couldn\'t cleared Custom\n-1= Order Failed\n0= Order enlisted\n1= Delivered Successfully\n2= On consignment',
  `Message` MEDIUMTEXT NULL,
  PRIMARY KEY (`order_id`, `payment_id`, `users_id`, `wh_origin_id`, `percels_id`, `supplier_charge_id`),
  INDEX `fk_orders_payments1_idx` (`payment_id` ASC) ,
  INDEX `fk_orders_users1_idx` (`users_id` ASC) ,
  INDEX `fk_orders_warehouses1_idx` (`wh_origin_id` ASC) ,
  INDEX `fk_orders_warehouses2_idx` (`wh_destination_id` ASC) ,
  INDEX `fk_orders_percels1_idx` (`percels_id` ASC) ,
  INDEX `fk_orders_tns_consignment1_idx` (`tns_consignmen_id` ASC) ,
  INDEX `fk_orders_supplier_charges1_idx` (`supplier_charge_id` ASC) ,
  CONSTRAINT `fk_orders_payments1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `eezyshipper`.`payments` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_warehouses1`
    FOREIGN KEY (`wh_origin_id`)
    REFERENCES `eezyshipper`.`warehouses` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_warehouses2`
    FOREIGN KEY (`wh_destination_id`)
    REFERENCES `eezyshipper`.`warehouses` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_percels1`
    FOREIGN KEY (`percels_id`)
    REFERENCES `eezyshipper`.`percels` (`percels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_tns_consignment1`
    FOREIGN KEY (`tns_consignmen_id`)
    REFERENCES `eezyshipper`.`tns_consignment` (`tns_cons_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_supplier_charges1`
    FOREIGN KEY (`supplier_charge_id`)
    REFERENCES `eezyshipper`.`supplier_charges` (`supplier_charge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`packages` (
  `varifies_id` INT NOT NULL AUTO_INCREMENT,
  `percels_id` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `content` VARCHAR(30) NULL,
  `product_image` VARCHAR(255) NULL COMMENT 'Maximum 4 images a user can upload and total images size would be 20MB',
  `product_status` ENUM('0', '1', '-1') NULL DEFAULT '1' COMMENT '0=Damaged/other\n1=ok\n-1=prohibited',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`varifies_id`),
  INDEX `fk_packages_percels1_idx` (`percels_id` ASC) ,
  CONSTRAINT `fk_packages_percels1`
    FOREIGN KEY (`percels_id`)
    REFERENCES `eezyshipper`.`percels` (`percels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eezyshipper`.`reset_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eezyshipper`.`reset_password` (
  `reset_password_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `query_hash` VARCHAR(500) NOT NULL,
  `status` ENUM('0', '1') NULL DEFAULT '0',
  `tkn_expire_timestamp` DATETIME NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`reset_password_id`, `users_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `query_hash_UNIQUE` (`query_hash` ASC) ,
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) ,
  INDEX `fk_reset_password_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_reset_password_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eezyshipper`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
